truncate table history;
truncate table test;
insert test (id,name) values(1,'1');
insert test (id,name) values(2,'2');
insert test (id,name) values(3,'3');
insert test (id,name) values(4,'4');
insert test (id,name) values(5,'5');
insert test (id,name) values(6,'6');
insert test (id,name) values(7,'7');
insert test (id,name) values(8,'8');
insert test (id,name) values(9,'9');
insert test (id,name) values(10,'10');
insert test (id,name) values(11,'11');
insert test (id,name) values(12,'12');
insert test (id,name) values(13,'13');
insert test (id,name) values(14,'14');
insert test (id,name) values(15,'15');
insert test (id,name) values(16,'16');
insert test (id,name) values(17,'17');
insert test (id,name) values(18,'18');